version: "3" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
    showniq-shopfi_api_production: #This is the name of our Nextjs application.
        image: "showniq-shopfi_api_production"
        build: #This specifies the location of our Dockerfile
            context: . #This specifies the location of our Dockerfile
            dockerfile: ./Dockerfile
        ports: #This is used to map the container’s ports to the host machine.
            - "7009:7009"
        restart: always
