module.exports = {
  STAFF_ERROR: {
    DUPLICATED_USER: "DUPLICATED_USER",
    DUPLICATED_USER_EMAIL: "DUPLICATED_USER_EMAIL",
    DUPLICATED_USER_PHONE: "DUPLICATED_USER_PHONE",
    NOT_AUTHORIZED: "NOT_AUTHORIZED",
    USER_LOCKED: "USER_LOCKED"
  }
}